import type { Project, Service, Photo, Reel } from "@/types";
import { cloudinaryImage, cloudinaryVideo } from "./cloudinary";

export const PROJECTS: Project[] = [
  {
    id: "sunflowers",
    title: "She Asked for Sunflowers",
    role: "Director · DOP · Editor · Actor",
    poster: cloudinaryImage("She_asked_for_Sunflowers_u8xqju"),
    video: cloudinaryVideo("SHE_ASKED_FOR_SUNFLOWERS_id1iwo"),
    youtubeUrl: "https://www.youtube.com/watch?v=9-eI6zji-nM&list=RD9-eI6zji-nM&start_radio=1",
    badges: ["He Stars In This"],
    year: 2024,
    category: "narrative",
    description:
      "A raw, emotional Kannada short about longing and unrequited love, shot amidst the sunflower fields of rural Karnataka. Pratham stars, directs, and frames every aching moment himself.",
  },
  {
    id: "christmas",
    title: "The Christmas Guest",
    role: "Director · DOP",
    poster: cloudinaryImage("The_Christmas_Guest_aqgt7x"),
    video: cloudinaryVideo("The_Christmas_Guest_A_Short_Film_That_Will_Stay_With_You_-_Talon_Production_House_144p_aqxk6u"),
    youtubeUrl: "https://www.youtube.com/watch?v=xCKz8NzoLMA&t=2s",
    badges: ["Dada Saheb Phalke Selected"],
    year: 2023,
    category: "narrative",
    description:
      "A Dada Saheb Phalke Film Festival selection. A quiet, luminous story about the strangers who change us. Shot with festive Christmas lights bleeding warmth into Bengaluru's midnight streets.",
  },
  {
    id: "coffee",
    title: "Before The Coffee Gets Cold",
    role: "Director · DOP · Editor",
    poster: cloudinaryImage("Before_The_Coffee_Gets_Cold_y60aty"),
    video: cloudinaryVideo("Before_The_Coffee_Gets_Cold_fhvaao"),
    youtubeUrl: "https://www.youtube.com/watch?v=udKE1I5-kYc",
    badges: [],
    year: 2024,
    category: "narrative",
    description:
      "Time, memory, and the bittersweet ritual of morning coffee. A meditative Kannada short that asks: what would you say if you had one more moment?",
  },
  {
    id: "dot",
    title: "DOT.",
    role: "Director · DOP",
    poster: cloudinaryImage("DOT._tmlaig"),
    video: cloudinaryVideo("DOT._I_KANNADA_SHORT_FILM_swxfw5"),
    youtubeUrl: "https://www.youtube.com/watch?v=jDI1HEvI7gE",
    badges: [],
    year: 2024,
    category: "narrative",
    description:
      "A single frame. A single feeling. DOT. is Pratham's most experimental short, a visual poem about existence stripped down to its most elemental form.",
  },
  {
    id: "sees-kaddi",
    title: "Sees Kaddi",
    role: "Actor",
    poster: cloudinaryImage("sees_kaddi_dp52bc"),
    video: cloudinaryVideo("Sees_Kaddi-Trailer_awtp8z"),
    isFeatureFilm: true,
    trailerYoutubeUrl: "https://www.youtube.com/watch?v=wrLF5JOYJd4",
    externalWatchUrl:
      "https://www.primevideo.com/dp/amzn1.dv.gti.67118027-540e-43a9-883d-a241c2da1dea?autoplay=0&ref_=atv_cf_strg_wb",
    externalWatchLabel: "Amazon Prime",
    badges: ["Acting Reel"],
    year: 2023,
    category: "acting",
    description:
      "Stepping in front of the lens for the first time. Pratham's acting debut, a deeply personal performance that proved the director understands his actors because he has been one.",
  },
  {
    id: "nasheya-gungale",
    title: "Nasheya Gungale",
    role: "Line Producer",
    poster: cloudinaryImage("Nasheya-Gungale__Potrait_nojbus"),
    posterLandscape: cloudinaryImage("Nasheya_Gungale_ad9qcs"),
    video: cloudinaryVideo("Nasheya_Gungale_Music_Video_pihf6d"),
    youtubeUrl: "https://www.youtube.com/watch?v=9dlbKgxvg_A&list=RD9dlbKgxvg_A&start_radio=1",
    badges: [],
    year: 2025,
    category: "commercial",
    description:
      "A high-energy Kannada music video brought to life on set as Line Producer, keeping the shoot running so the performance and visuals could shine.",
  },
];

export const SERVICES: Service[] = [
  {
    id: "narrative",
    title: "Narrative Shorts & Indie Kannada Films",
    description:
      "Emotionally raw stories that chase feelings, not formulas. From concept to final grade, Pratham brings the full weight of a festival-selected filmmaker to every project.",
    color: "#7EADA9",
    icon: "film",
    videoLoop: cloudinaryVideo("Sees_Kaddi-Trailer_awtp8z"),
  },
  {
    id: "commercial",
    title: "Commercial & Brand Films",
    description:
      "Visual stories that make brands unforgettable. Cinematic storytelling applied to your product, because great brands deserve more than ads. They deserve films.",
    color: "#1F5560",
    icon: "star",
    videoLoop: cloudinaryVideo("JEWELLERY_AD_zzdsjb"),
  },
  {
    id: "dop",
    title: "DOP · Editing · Color Grading",
    description:
      "Hire the eye. Phalke-selected. Full post-production pipeline, from set to screen, with obsessive cinematic precision and that signature Kannada golden-hour warmth.",
    color: "#F8F4ED",
    icon: "aperture",
    videoLoop: cloudinaryVideo("DOT_TEASER_fzvnic"),
  },
];

export const ABOUT_FRAMES: { year: string; title: string; description: string; image: string; hasVideo?: boolean }[] = [
  {
    year: "2006",
    title: "Born in Mysuru",
    description: "Under golden-hour Karnataka skies, in the shadow of a palace. Pratham Raje Urs draws first breath.",
    image: cloudinaryImage("BEACH_1-01_qhvnl0"),
  },
  {
    year: "2016",
    title: "First Frame",
    description: "A smartphone. A sunlit lane. The first time light was trapped in a frame. Nothing was ever the same.",
    image: cloudinaryImage("DSC01296_rg69c2"),
    hasVideo: true,
  },
  {
    year: "2023",
    title: "Sees Kaddi · Actor",
    description: "The director steps in front of the lens. Understanding the actor's vulnerability from the inside.",
    image: cloudinaryImage("Sees_Kaddi_Landscape_f2y5dm"),
  },
  {
    year: "2024",
    title: "Talon Production House",
    description: "Founded in Bengaluru. A home for Kannada stories that dare to feel something.",
    image: cloudinaryImage("final-1_tuohjh"),
  },
  {
    year: "Now",
    title: "Still Chasing Feelings",
    description: "Every frame. Every film. Still chasing that one perfect feeling.",
    image: cloudinaryImage("DSC01047_twths2"),
  },
];

/* ─── Photography ────────────────────────────────────────────────────────── */

export const PHOTOS: Photo[] = [
  { id: 1, src: cloudinaryImage("She_asked_for_Sunflowers_u8xqju"), alt: "Golden-hour sunflower field", project: "She Asked for Sunflowers", year: "2024", category: "film-stills", role: "Director | DOP", btsNote: "Shot entirely during a 15-minute magic hour window before the storm hit.", aspect: "tall", exif: { camera: "Sony FX3", lens: "Sigma 35mm f/1.4", aperture: "f/1.4", iso: "800", shutter: "1/500" }, isThumbnail: true, width: 2047, height: 2560 },
  { id: 2, src: cloudinaryImage("DSC01336_ae95n6"), alt: "Rain-streaked cafe window portrait", project: "Before The Coffee Gets Cold", year: "2024", category: "portraits", role: "DOP", btsNote: "Used a custom prism filter to catch the neon reflections off the wet window.", aspect: "wide", exif: { camera: "Sony A7III", lens: "85mm f/1.8", aperture: "f/1.8", iso: "640", shutter: "1/200" }, width: 4608, height: 2592 },
  { id: 3, src: cloudinaryImage("The_Christmas_Guest_aqgt7x"), alt: "Festive living room, warm light", project: "The Christmas Guest", year: "2023", category: "film-stills", role: "Director", btsNote: "We lit the entire scene using only practical tungsten bulbs and the Christmas tree lights.", aspect: "square", isThumbnail: true, width: 1600, height: 900 },
  { id: 4, src: cloudinaryImage("DSC01177_p6nv4s"), alt: "Red umbrella in monsoon cobblestones", project: "Mysuru Streets", year: "2024", category: "street", role: "Photographer", aspect: "tall", width: 2592, height: 4608 },
  { id: 5, src: cloudinaryImage("BEACH_1-11_bdyywp"), alt: "Golden-hour garden ceremony", project: "Wedding Cinema: Talon", year: "2025", category: "portraits", role: "Director | Editor", btsNote: "Captured on a vintage 35mm lens to give the digital sensor an organic, timeless feel.", aspect: "wide", width: 7008, height: 3944 },
  { id: 6, src: cloudinaryImage("DOT._tmlaig"), alt: "Silhouette against concrete wall", project: "DOT.", year: "2024", category: "film-stills", role: "DOP", btsNote: "The stark contrast was achieved with a single 10K light positioned 50 feet down the alley.", aspect: "tall", isThumbnail: true, width: 1097, height: 866 },
  { id: 7, src: cloudinaryImage("DSC01182_w1mmvq"), alt: "Blue-hour rooftop shoot", project: "Behind The Frame", year: "2025", category: "bts", role: "Director", aspect: "wide", width: 4608, height: 2592 },
  { id: 8, src: cloudinaryImage("BEACH_1-03_mc0nra"), alt: "Karnataka sunrise paddy fields", project: "Karnataka Diaries", year: "2023", category: "landscapes", role: "DOP | Drone Op", btsNote: "Woke up at 4 AM to hike 3 miles just to catch the morning mist rolling off the fields.", aspect: "wide", width: 7008, height: 3944 },
  { id: 9, src: cloudinaryImage("sees_kaddi_dp52bc"), alt: "Night alley, dramatic sidelight", project: "Sees Kaddi", year: "2023", category: "film-stills", role: "Actor | Co-Director", aspect: "tall", isThumbnail: true, width: 278, height: 417 },
  { id: 10, src: cloudinaryImage("DSC01322_ztuwfa"), alt: "Ancient temple archway at dawn", project: "Karnataka Diaries", year: "2023", category: "landscapes", role: "Photographer", aspect: "tall", width: 2592, height: 4608 },
  { id: 11, src: "/images/HeadShot_Pratham.jpeg", alt: "Director portrait with camera", project: "Self Portrait", year: "2024", category: "portraits", role: "Self", aspect: "tall", width: 1067, height: 1600 },
  { id: 12, src: cloudinaryImage("Sees_Kaddi_Landscape_f2y5dm"), alt: "Wide landscape from Sees Kaddi set", project: "Sees Kaddi", year: "2023", category: "bts", role: "Behind the Scenes", aspect: "wide", isThumbnail: true, width: 1080, height: 608 },
  { id: 13, src: cloudinaryImage("DSC01038-299_z68kmu"), alt: "Monsoon bridge silhouette", project: "Mysuru Monsoon", year: "2024", category: "street", role: "Photographer", aspect: "tall", width: 2453, height: 4354 },
  { id: 14, src: cloudinaryImage("DSC01055_xxbbwd"), alt: "Chai stall at dusk", project: "Mysuru Streets", year: "2024", category: "street", role: "Photographer", aspect: "wide", width: 4608, height: 2592 },
  { id: 15, src: cloudinaryImage("DSC01235_boqwov"), alt: "Lens flare portrait on set", project: "Talon BTS", year: "2025", category: "bts", role: "Behind the Scenes", aspect: "square", width: 2338, height: 2576 },
  { id: 16, src: cloudinaryImage("BEACH_1-02_cskcde"), alt: "Golden hour over rice paddies", project: "Karnataka Diaries", year: "2023", category: "landscapes", role: "Photographer", aspect: "wide", width: 7008, height: 3944 },
  { id: 17, src: cloudinaryImage("DSC01035-2_pbivoi"), alt: "Actor closeup between takes", project: "She Asked for Sunflowers", year: "2024", category: "portraits", role: "DOP", aspect: "tall", width: 2592, height: 4400 },
  { id: 18, src: cloudinaryImage("BEACH_1-05_cmeemu"), alt: "Crew silhouette at magic hour", project: "Talon BTS", year: "2025", category: "bts", role: "Behind the Scenes", aspect: "wide", width: 7008, height: 3944 },
  { id: 19, src: cloudinaryImage("BEACH_1-09_kjpjja"), alt: "Mysuru Palace illuminated at night", project: "Karnataka Diaries", year: "2023", category: "landscapes", role: "Photographer", aspect: "wide", width: 6676, height: 3757 },
  { id: 20, src: cloudinaryImage("DSC01154_gqvyap"), alt: "Coffee steam in morning light", project: "Before The Coffee Gets Cold", year: "2024", category: "film-stills", role: "DOP", aspect: "square", width: 4608, height: 3072 },
  { id: 21, src: cloudinaryImage("DSC012244_ozwtna"), alt: "Rain on window with bokeh lights", project: "The Christmas Guest", year: "2023", category: "film-stills", role: "Director", aspect: "tall", width: 2592, height: 4608 },
  { id: 22, src: cloudinaryImage("DSC01225_bgqrzn"), alt: "Street lamp in fog", project: "Mysuru Streets", year: "2024", category: "street", role: "Photographer", aspect: "tall", width: 2592, height: 4608 },
  { id: 23, src: cloudinaryImage("DSC01332_nclvxr"), alt: "Director's chair on set", project: "Talon BTS", year: "2025", category: "bts", role: "Behind the Scenes", aspect: "square", width: 2592, height: 4608 },
  { id: 24, src: cloudinaryImage("BEACH_1-17_jntr4z"), alt: "Sunset along the Karnataka coast", project: "Karnataka Diaries", year: "2023", category: "landscapes", role: "Photographer", aspect: "wide", width: 7008, height: 3944 },
  { id: 25, src: cloudinaryImage("DSC01224_lb6vmp"), alt: "Candid couple at reception", project: "Wedding Cinema: Talon", year: "2025", category: "portraits", role: "Director", aspect: "tall", width: 2592, height: 4608 },
  { id: 26, src: cloudinaryImage("DSC01296_rg69c2"), alt: "Photography by Pratham Raje Urs — frame 26", aspect: "tall", width: 2592, height: 4608 },
  { id: 27, src: cloudinaryImage("DSC01047_twths2"), alt: "Photography by Pratham Raje Urs — frame 27", aspect: "tall", width: 2592, height: 4608 },
  { id: 28, src: cloudinaryImage("DSC01181_pu3s1q"), alt: "Photography by Pratham Raje Urs — frame 28", aspect: "tall", width: 2592, height: 4608 },
  { id: 29, src: cloudinaryImage("DSC01041-2_i9htqq"), alt: "Photography by Pratham Raje Urs — frame 29", aspect: "tall", width: 2592, height: 4077 },
  { id: 30, src: cloudinaryImage("DSC01329_ir9f96"), alt: "Photography by Pratham Raje Urs — frame 30", aspect: "wide", width: 4608, height: 2592 },
  { id: 31, src: cloudinaryImage("DSC01313_2_epu7uo"), alt: "Photography by Pratham Raje Urs — frame 31", aspect: "tall", width: 2592, height: 4608 },
  { id: 32, src: cloudinaryImage("DSC01311_pnc3jp"), alt: "Photography by Pratham Raje Urs — frame 32", aspect: "wide", width: 4608, height: 2592 },
  { id: 33, src: cloudinaryImage("DSC01293_xzvnv1"), alt: "Photography by Pratham Raje Urs — frame 33", aspect: "tall", width: 2592, height: 4608 },
  { id: 34, src: cloudinaryImage("IMAGE_-07_fj5akc"), alt: "Photography by Pratham Raje Urs — frame 34", aspect: "wide", width: 6000, height: 3376 },
  { id: 35, src: cloudinaryImage("IMAGE_-06_fed37a"), alt: "Photography by Pratham Raje Urs — frame 35", aspect: "wide", width: 6000, height: 3376 },
  { id: 36, src: cloudinaryImage("ADJ06996_o2rzoq"), alt: "Photography by Pratham Raje Urs — frame 36", aspect: "tall", width: 2592, height: 3240 },
  { id: 37, src: cloudinaryImage("ADJ06985_npz6tz"), alt: "Photography by Pratham Raje Urs — frame 37", aspect: "tall", width: 2592, height: 3240 },
  { id: 38, src: cloudinaryImage("ADJ06956_czbwi9"), alt: "Photography by Pratham Raje Urs — frame 38", aspect: "tall", width: 2592, height: 3240 },
  { id: 39, src: cloudinaryImage("ADJ06939_oag6lh"), alt: "Photography by Pratham Raje Urs — frame 39", aspect: "tall", width: 2244, height: 2805 },
  { id: 40, src: cloudinaryImage("ADJ06937_sha6ye"), alt: "Photography by Pratham Raje Urs — frame 40", aspect: "tall", width: 1678, height: 2097 },
  { id: 41, src: cloudinaryImage("VInita_Portfolio-11_ubwaj4"), alt: "Photography by Pratham Raje Urs — Vinita Portfolio", aspect: "tall", width: 3072, height: 4480 },
  { id: 42, src: cloudinaryImage("VInita_Portfolio-10_v1sfhm"), alt: "Photography by Pratham Raje Urs — Vinita Portfolio", aspect: "tall", width: 2592, height: 4608 },
  { id: 43, src: cloudinaryImage("VInita_Portfolio-9_d2ufdq"), alt: "Photography by Pratham Raje Urs — Vinita Portfolio", aspect: "tall", width: 2468, height: 3290 },
  { id: 44, src: cloudinaryImage("VInita_Portfolio-7_pwbicz"), alt: "Photography by Pratham Raje Urs — Vinita Portfolio", aspect: "tall", width: 2181, height: 2963 },
  { id: 45, src: cloudinaryImage("VInita_Portfolio-2-2_a9xhu5"), alt: "Photography by Pratham Raje Urs — Vinita Portfolio 2", aspect: "tall", width: 2592, height: 4608 },
  { id: 46, src: cloudinaryImage("VInita_Portfolio-2_rpqdaa"), alt: "Photography by Pratham Raje Urs — Vinita Portfolio", aspect: "tall", width: 5184, height: 9216 },
  { id: 47, src: cloudinaryImage("shradha_team-16_dzhprb"), alt: "Photography by Pratham Raje Urs — Shradha Team", aspect: "wide", width: 6876, height: 3870 },
  { id: 48, src: cloudinaryImage("shradha_team-15_ttnb1f"), alt: "Photography by Pratham Raje Urs — Shradha Team", aspect: "wide", width: 6928, height: 3899 },
  { id: 49, src: cloudinaryImage("shradha_team-14_apndxu"), alt: "Photography by Pratham Raje Urs — Shradha Team", aspect: "wide", width: 7008, height: 3944 },
  { id: 50, src: cloudinaryImage("shradha_team-13_gqq9dg"), alt: "Photography by Pratham Raje Urs — Shradha Team", aspect: "wide", width: 6945, height: 3909 },
  { id: 51, src: cloudinaryImage("shradha_team-12_m7dn01"), alt: "Photography by Pratham Raje Urs — Shradha Team", aspect: "wide", width: 7008, height: 3944 },
  { id: 52, src: cloudinaryImage("shradha_team-11_onio03"), alt: "Photography by Pratham Raje Urs — Shradha Team", aspect: "wide", width: 5921, height: 3836 },
  { id: 53, src: cloudinaryImage("shradha_team-10_zdbrx4"), alt: "Photography by Pratham Raje Urs — Shradha Team", aspect: "wide", width: 6975, height: 4072 },
  { id: 54, src: cloudinaryImage("shradha_team-09_xknsnk"), alt: "Photography by Pratham Raje Urs — Shradha Team", aspect: "wide", width: 7008, height: 4672 },
  { id: 55, src: cloudinaryImage("shradha_team-08_yexg9p"), alt: "Photography by Pratham Raje Urs — Shradha Team", aspect: "wide", width: 6370, height: 3826 },
  { id: 56, src: cloudinaryImage("shradha_team-07_pgfsgv"), alt: "Photography by Pratham Raje Urs — Shradha Team", aspect: "wide", width: 7008, height: 3944 },
  { id: 57, src: cloudinaryImage("shradha_team-06_oguj8i"), alt: "Photography by Pratham Raje Urs — Shradha Team", aspect: "tall", width: 3944, height: 7008 },
  { id: 58, src: cloudinaryImage("shradha_team-05_qfbsyd"), alt: "Photography by Pratham Raje Urs — Shradha Team", aspect: "wide", width: 6616, height: 3394 },
  { id: 59, src: cloudinaryImage("shradha_team-04_po9pyy"), alt: "Photography by Pratham Raje Urs — Shradha Team", aspect: "wide", width: 6238, height: 3822 },
  { id: 60, src: cloudinaryImage("shradha_team-03_uaswej"), alt: "Photography by Pratham Raje Urs — Shradha Team", aspect: "wide", width: 7008, height: 3944 },
  { id: 61, src: cloudinaryImage("shradha_team-02_aerhzm"), alt: "Photography by Pratham Raje Urs — Shradha Team", aspect: "wide", width: 4991, height: 4068 },
  { id: 62, src: cloudinaryImage("shradha_team-01_dal4gm"), alt: "Photography by Pratham Raje Urs — Shradha Team", aspect: "wide", width: 7008, height: 4319 },
  { id: 63, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-50_yync0e"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 64, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-49_wrvsnh"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 65, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-48_omh1ty"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 66, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-47_smzkb8"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 67, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-46_mgvzp2"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 68, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-45_bhehig"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2011, height: 3576 },
  { id: 69, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-44_nbg8kg"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 70, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-43_h7zz47"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 71, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-42_a8vhvk"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 72, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-41_p3avmd"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2370, height: 4213 },
  { id: 73, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-40_zmkpgi"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 74, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-39_soa5ba"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2586, height: 3879 },
  { id: 75, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-38_pg3101"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 76, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-37_pkhtsm"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 77, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-34_z90pe6"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 78, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-36_olxzat"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 79, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-33_wwwczq"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 80, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-35_fmeyqq"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 81, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-32_xcwinm"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 82, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-31_rnpau5"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 83, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-29_ggedzu"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 84, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-30_hhnofv"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 85, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-28_inepqo"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2248, height: 3997 },
  { id: 86, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-27_jninnz"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2609, height: 3479 },
  { id: 87, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-23_sgzbms"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 88, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-26_rfaxhm"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2836, height: 4254 },
  { id: 89, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-25_owcnsk"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 90, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-24_qarexz"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 91, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-22_iaulde"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 92, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-21_ztg1vd"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 93, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-20_oikjl8"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 94, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-19_jxcb7n"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 95, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-18_jcxfoz"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 96, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-16_jheudg"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 1772, height: 3150 },
  { id: 97, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-17_xobjv4"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 98, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-14_kbbomx"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 99, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-15_vlcgrr"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 1999, height: 3554 },
  { id: 100, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-13_cx8nn3"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 101, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-12_cox3ee"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 102, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-11_uoneer"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 103, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-9_djezox"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 104, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-7_fjqxvr"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 105, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-10_kuqhjb"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 106, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-8_yexsne"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 107, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-3_afe3hc"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2592, height: 4608 },
  { id: 108, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-6_m610rq"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2046, height: 3638 },
  { id: 109, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-5_qmirgq"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2592, height: 4608 },
  { id: 110, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-4_mngsea"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2592, height: 4608 },
  { id: 111, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT-2_uyuej3"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2592, height: 4608 },
  { id: 112, src: cloudinaryImage("INDYVARNA_MAY_OUTFIT_bznzsg"), alt: "Photography by Pratham Raje Urs — Indyvarna May Outfit", aspect: "tall", width: 2457, height: 3685 },
  { id: 113, src: cloudinaryImage("IMAGE_-20_aq50bh"), alt: "Photography by Pratham Raje Urs — frame 113", aspect: "wide", width: 6000, height: 3376 },
  { id: 114, src: cloudinaryImage("IMAGE_-19_koares"), alt: "Photography by Pratham Raje Urs — frame 114", aspect: "wide", width: 6000, height: 3376 },
  { id: 115, src: cloudinaryImage("IMAGE_-18_jvh9hy"), alt: "Photography by Pratham Raje Urs — frame 115", aspect: "wide", width: 3096, height: 1743 },
  { id: 116, src: cloudinaryImage("IMAGE_-17_i3nojj"), alt: "Photography by Pratham Raje Urs — frame 116", aspect: "wide", width: 6000, height: 3376 },
  { id: 117, src: cloudinaryImage("IMAGE_-16_khguzy"), alt: "Photography by Pratham Raje Urs — frame 117", aspect: "wide", width: 3936, height: 2216 },
  { id: 118, src: cloudinaryImage("IMAGE_-15_lqnvdh"), alt: "Photography by Pratham Raje Urs — frame 118", aspect: "wide", width: 3936, height: 2216 },
  { id: 119, src: cloudinaryImage("IMAGE_-14_apjife"), alt: "Photography by Pratham Raje Urs — frame 119", aspect: "wide", width: 6000, height: 3376 },
  { id: 120, src: cloudinaryImage("IMAGE_-12_ynydq5"), alt: "Photography by Pratham Raje Urs — frame 120", aspect: "wide", width: 6000, height: 3376 },
  { id: 121, src: cloudinaryImage("IMAGE_-11_b6ofm8"), alt: "Photography by Pratham Raje Urs — frame 121", aspect: "wide", width: 6000, height: 3376 },
  { id: 122, src: cloudinaryImage("IMAGE_-10_rdlgmq"), alt: "Photography by Pratham Raje Urs — frame 122", aspect: "wide", width: 6000, height: 3376 },
  { id: 123, src: cloudinaryImage("IMAGE_-09_klrtif"), alt: "Photography by Pratham Raje Urs — frame 123", aspect: "wide", width: 6000, height: 3376 },
  { id: 124, src: cloudinaryImage("IMAGE_-04_vgymwh"), alt: "Photography by Pratham Raje Urs — frame 124", aspect: "wide", width: 6000, height: 3376 },
  { id: 125, src: cloudinaryImage("IMAGE_-05_lffu2f"), alt: "Photography by Pratham Raje Urs — frame 125", aspect: "wide", width: 4843, height: 2725 },
  { id: 126, src: cloudinaryImage("IMAGE_-01_hwkehj"), alt: "Photography by Pratham Raje Urs — frame 126", aspect: "wide", width: 6000, height: 3376 },
  { id: 127, src: cloudinaryImage("IMAGE_-03_s8espp"), alt: "Photography by Pratham Raje Urs — frame 127", aspect: "wide", width: 6000, height: 3376 },
  { id: 128, src: cloudinaryImage("IMAGE_-02_o0xw3u"), alt: "Photography by Pratham Raje Urs — frame 128", aspect: "wide", width: 6000, height: 3376 },
  { id: 129, src: cloudinaryImage("final-1_tuohjh"), alt: "Photography by Pratham Raje Urs — Final", aspect: "square", width: 2672, height: 2826 },
  { id: 130, src: cloudinaryImage("final_5_iz3etd"), alt: "Photography by Pratham Raje Urs — Final", aspect: "tall", width: 3944, height: 7008 },
  { id: 131, src: cloudinaryImage("final_4_z5slob"), alt: "Photography by Pratham Raje Urs — Final", aspect: "tall", width: 3944, height: 7008 },
  { id: 132, src: cloudinaryImage("final_3_twiquu"), alt: "Photography by Pratham Raje Urs — Final", aspect: "tall", width: 3749, height: 6659 },
  { id: 133, src: cloudinaryImage("DSC01397_oh9tk3"), alt: "Photography by Pratham Raje Urs — frame 133", aspect: "tall", width: 2592, height: 4608 },
  { id: 134, src: cloudinaryImage("DSC01376_dotmcv"), alt: "Photography by Pratham Raje Urs — frame 134", aspect: "tall", width: 2181, height: 3878 },
  { id: 135, src: cloudinaryImage("DSC01263_mvi4cc"), alt: "Photography by Pratham Raje Urs — frame 135", aspect: "wide", width: 4608, height: 2592 },
  { id: 136, src: cloudinaryImage("DSC01369_voch9l"), alt: "Photography by Pratham Raje Urs — frame 136", aspect: "wide", width: 4608, height: 2592 },
  { id: 137, src: cloudinaryImage("DSC01278_ezbdmq"), alt: "Photography by Pratham Raje Urs — frame 137", aspect: "tall", width: 2592, height: 4608 },
  { id: 138, src: cloudinaryImage("DSC01275_pw3zsi"), alt: "Photography by Pratham Raje Urs — frame 138", aspect: "tall", width: 2592, height: 4608 },
  { id: 139, src: cloudinaryImage("DSC01262_s8b80e"), alt: "Photography by Pratham Raje Urs — frame 139", aspect: "wide", width: 4608, height: 2592 },
  { id: 140, src: cloudinaryImage("DSC01254_ukhwkk"), alt: "Photography by Pratham Raje Urs — frame 140", aspect: "tall", width: 2592, height: 4608 },
  { id: 141, src: cloudinaryImage("DSC01253_brx6mu"), alt: "Photography by Pratham Raje Urs — frame 141", aspect: "tall", width: 2592, height: 4608 },
  { id: 142, src: cloudinaryImage("DSC01234_ziwxqq"), alt: "Photography by Pratham Raje Urs — frame 142", aspect: "tall", width: 1190, height: 2116 },
  { id: 143, src: cloudinaryImage("DSC01170_ka3vhz"), alt: "Photography by Pratham Raje Urs — frame 143", aspect: "tall", width: 2203, height: 3916 },
  { id: 144, src: cloudinaryImage("DSC01155_b0kmvt"), alt: "Photography by Pratham Raje Urs — frame 144", aspect: "wide", width: 4608, height: 2592 },
  { id: 145, src: cloudinaryImage("DSC01168_t9ux6k"), alt: "Photography by Pratham Raje Urs — frame 145", aspect: "tall", width: 2268, height: 4032 },
  { id: 146, src: cloudinaryImage("DSC01142_sbjo9o"), alt: "Photography by Pratham Raje Urs — frame 146", aspect: "tall", width: 2592, height: 4608 },
  { id: 147, src: cloudinaryImage("DSC01137_rpc9hx"), alt: "Photography by Pratham Raje Urs — frame 147", aspect: "tall", width: 2592, height: 4608 },
  { id: 148, src: cloudinaryImage("DSC00974_mxewct"), alt: "Photography by Pratham Raje Urs — frame 148", aspect: "tall", width: 2592, height: 4608 },
  { id: 149, src: cloudinaryImage("DSC00970_d5ot99"), alt: "Photography by Pratham Raje Urs — frame 149", aspect: "tall", width: 2592, height: 4608 },
  { id: 150, src: cloudinaryImage("DSC00950_g5ai2c"), alt: "Photography by Pratham Raje Urs — frame 150", aspect: "wide", width: 7008, height: 4672 },
  { id: 151, src: cloudinaryImage("BEACH_1-20_wpxmup"), alt: "Photography by Pratham Raje Urs — Beach 1", aspect: "wide", width: 7008, height: 3944 },
  { id: 152, src: cloudinaryImage("BEACH_1-19_jnhqvh"), alt: "Photography by Pratham Raje Urs — Beach 1", aspect: "wide", width: 7008, height: 3944 },
  { id: 153, src: cloudinaryImage("BEACH_1-14_kb5bcb"), alt: "Photography by Pratham Raje Urs — Beach 1", aspect: "wide", width: 6089, height: 3427 },
  { id: 154, src: cloudinaryImage("BEACH_1-18_nd6kjw"), alt: "Photography by Pratham Raje Urs — Beach 1", aspect: "wide", width: 7008, height: 3944 },
  { id: 155, src: cloudinaryImage("BEACH_1-12_m91ntn"), alt: "Photography by Pratham Raje Urs — Beach 1", aspect: "wide", width: 7008, height: 3944 },
  { id: 156, src: cloudinaryImage("BEACH_1-16_mlakgm"), alt: "Photography by Pratham Raje Urs — Beach 1", aspect: "wide", width: 5648, height: 3682 },
  { id: 157, src: cloudinaryImage("BEACH_1-15_jsiw4w"), alt: "Photography by Pratham Raje Urs — Beach 1", aspect: "wide", width: 4608, height: 2592 },
  { id: 158, src: cloudinaryImage("BEACH_1-13_vh15vc"), alt: "Photography by Pratham Raje Urs — Beach 1", aspect: "wide", width: 7008, height: 3944 },
  { id: 159, src: cloudinaryImage("BEACH_1-10_vujuli"), alt: "Photography by Pratham Raje Urs — Beach 1", aspect: "tall", width: 3889, height: 5768 },
  { id: 160, src: cloudinaryImage("ADJ07054_u0ctiz"), alt: "Photography by Pratham Raje Urs — frame 160", aspect: "tall", width: 2592, height: 3240 },
  { id: 161, src: cloudinaryImage("BEACH_1-08_w7pjgh"), alt: "Photography by Pratham Raje Urs — Beach 1", aspect: "wide", width: 7008, height: 3944 },
  { id: 162, src: cloudinaryImage("BEACH_1-07_kbziko"), alt: "Photography by Pratham Raje Urs — Beach 1", aspect: "wide", width: 5981, height: 3987 },
  { id: 163, src: cloudinaryImage("BEACH_1-06_x1mk6j"), alt: "Photography by Pratham Raje Urs — Beach 1", aspect: "wide", width: 7008, height: 3944 },
  { id: 164, src: cloudinaryImage("BEACH_1-04_wtzpqr"), alt: "Photography by Pratham Raje Urs — Beach 1", aspect: "wide", width: 6536, height: 4357 },
  { id: 165, src: cloudinaryImage("BEACH_1-01_qhvnl0"), alt: "Photography by Pratham Raje Urs — Beach 1", aspect: "wide", width: 7008, height: 3944 },
  { id: 166, src: cloudinaryImage("ADJ07037_zjiqkf"), alt: "Photography by Pratham Raje Urs — frame 166", aspect: "tall", width: 3656, height: 4570 },
];

/* ─── Reels ──────────────────────────────────────────────────────────────── */

export const REELS: Reel[] = [
  { id: "reel-sunflowers-bts", title: "Sunflowers BTS", description: "Behind the scenes of the sunflower field shoot at golden hour.", category: "bts", poster: cloudinaryImage("She_asked_for_Sunflowers_u8xqju"), videoSrc: "", duration: 32, featured: true, year: 2024 },
  { id: "reel-christmas-mood", title: "Christmas Mood Edit", description: "A 45-second mood reel from The Christmas Guest, all practical lights.", category: "narrative", poster: cloudinaryImage("The_Christmas_Guest_aqgt7x"), videoSrc: cloudinaryVideo("The_Christmas_Guest_A_Short_Film_That_Will_Stay_With_You_-_Talon_Production_House_144p_aqxk6u"), duration: 45, featured: true, year: 2023 },
  { id: "reel-coffee-teaser", title: "Before The Coffee Gets Cold — Teaser", description: "The official 30-second teaser cut for social.", category: "narrative", poster: cloudinaryImage("Before_The_Coffee_Gets_Cold_y60aty"), videoSrc: "", duration: 30, featured: true, year: 2024 },
  { id: "reel-dot-visual", title: "DOT. Visual Poem", description: "An experimental 60-second visual poem in monochrome.", category: "experimental", poster: cloudinaryImage("DOT._tmlaig"), videoSrc: cloudinaryVideo("DOT_TEASER_fzvnic"), duration: 60, year: 2024 },
  { id: "reel-talon-showreel", title: "Talon 2025 Showreel", description: "Talon Production House highlight reel — the year in frames.", category: "narrative", poster: cloudinaryImage("final-1_tuohjh"), videoSrc: cloudinaryVideo("Nasheya_Gungale_Music_Video_pihf6d"), duration: 58, year: 2025 },
  { id: "reel-wedding-highlights", title: "Wedding Highlights — Coastal", description: "A cinematic wedding film condensed into a 45-second reel.", category: "wedding", poster: cloudinaryImage("BEACH_1-11_bdyywp"), videoSrc: "", duration: 45, year: 2025 },
  { id: "reel-sees-kaddi-cut", title: "Sees Kaddi — Behind the Performance", description: "The raw acting process captured in 40 seconds.", category: "bts", poster: cloudinaryImage("sees_kaddi_dp52bc"), videoSrc: cloudinaryVideo("Sees_Kaddi-Trailer_awtp8z"), duration: 40, year: 2023 },
  { id: "reel-monsoon-mysuru", title: "Monsoon Mysuru", description: "Rain, cobblestones, and the quiet poetry of a monsoon walk.", category: "experimental", poster: cloudinaryImage("DSC01177_p6nv4s"), videoSrc: "", duration: 35, year: 2024 },
  { id: "reel-golden-hour-bts", title: "Golden Hour — How We Shoot It", description: "A 30-second breakdown of our golden hour lighting setup.", category: "bts", poster: cloudinaryImage("DSC01047_twths2"), videoSrc: "", duration: 30, year: 2025 },
  { id: "reel-karnataka-timelapse", title: "Karnataka Sunrise Timelapse", description: "Paddy fields at dawn, compressed into 20 breathtaking seconds.", category: "experimental", poster: cloudinaryImage("BEACH_1-03_mc0nra"), videoSrc: "", duration: 20, year: 2023 },
  { id: "reel-sunflower-poem", title: "Sunflowers — A Visual Letter", description: "A 50-second poetic edit from the sunflower fields of rural Karnataka.", category: "narrative", poster: cloudinaryImage("She_asked_for_Sunflowers_u8xqju"), videoSrc: "", duration: 50, year: 2024 },
  { id: "reel-wedding-ceremony", title: "Wedding Ceremony — Temple", description: "Traditional ceremony shot with anamorphic lenses, 40-second edit.", category: "wedding", poster: cloudinaryImage("BEACH_1-01_qhvnl0"), videoSrc: "", duration: 40, year: 2025 },
];

export const FEATURED_REELS: string[] = ["reel-sunflowers-bts", "reel-christmas-mood", "reel-coffee-teaser"];

/* ─── Navigation ─────────────────────────────────────────────────────────── */

export const NAV_ITEMS = [
  { id: "home", label: "Home", href: "#hero", clip: cloudinaryVideo("DOT_TEASER_fzvnic") },
  { id: "vault", label: "The Vault", href: "#vault", clip: cloudinaryVideo("Sees_Kaddi-Trailer_awtp8z") },
  { id: "photography", label: "Photography", href: "/photography", clip: cloudinaryVideo("JEWELLERY_AD_zzdsjb") },

  { id: "connect", label: "Connect", href: "#connect", clip: cloudinaryVideo("Shazia_Khan_AD_gnr0fo") },
];
